# StyLua configuration for Lua formatting
# https://github.com/JohnnyMorganz/StyLua

column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
